In [39]:
import pandas as pd
import numpy as np
df=pd.read_csv("C:/Users/ricru/Documents/df_sucio.csv")
df

Amount  Severity   Age Private Attorney  Marital Status  \
0       57041.0       7.0  62.0                1             NaN   
1      324976.0       6.0  38.0                1             2.0   
2      135383.0       4.0  34.0                1             2.0   
3      829742.0       7.0  42.0                1             1.0   
4      197675.0       3.0  60.0                0             2.0   
...         ...       ...   ...              ...             ...   
94589  146059.0       3.0  56.0                0             2.0   
94590  908341.0       8.0  35.0                1             2.0   
94591   39355.0       3.0  42.0                0             4.0   
94592  827167.0       6.0  57.0                1             0.0   
94593  134090.0       9.0  63.0                1             4.0   

                    Specialty          Insurance  Gender  
0             Family Practice            Private    Male  
1                         NaN       No Insurance  Female  
2                  Cardiology            Unknown    Male  
3                  Pediatrics       No Insurance  Female  
4                       OBGYN  Medicare/Medicaid  Female  
...                       ...                ...     ...  
94589                   OBGYN            Unknown  Female  
94590      Orthopedic Surgery            Unknown    Male  
94591      Emergency Medicine  Medicare/Medicaid    Male  
94592             Dermatology            Private    Male  
94593  Neurology/Neurosurgery  Medicare/Medicaid  Female  

[94594 rows x 8 columns]

In [40]:
df.shape

(94594, 8)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94594 entries, 0 to 94593
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Amount            91757 non-null  float64
 1   Severity          91757 non-null  float64
 2   Age               91757 non-null  float64
 3   Private Attorney  91757 non-null  object 
 4   Marital Status    89918 non-null  float64
 5   Specialty         91757 non-null  object 
 6   Insurance         91757 non-null  object 
 7   Gender            91757 non-null  object 
dtypes: float64(4), object(4)
memory usage: 5.8+ MB


In [42]:
lista= df.columns
lista

Index(['Amount', 'Severity', 'Age', 'Private Attorney', 'Marital Status',
       'Specialty', 'Insurance', 'Gender'],
      dtype='object')

In [43]:
df['Amount'].unique()

array([ 57041., 324976., 135383., ..., 923562., 140896.,  13784.],
      shape=(66270,))

In [44]:
df['Amount'].nunique()

66269

In [45]:
df['Severity'].unique()

array([ 7.,  6.,  4.,  3.,  9., nan,  1.,  5.,  2.,  8.])

In [46]:
df['Severity'].nunique()

9

In [47]:
df['Age'].unique()

array([62., 38., 34., 42., 60., 71., 50., 58., 37., 51., 23., nan, 57.,
       73., 43.,  4., 41., 39., 19., 27., 32., 16., 26., 35., 36., 69.,
        7., 24., 64., 68., 40., 80., 52., 61., 28., 55., 59.,  3., 11.,
       83., 74., 63., 76., 14., 77.,  9., 66., 20., 45., 31., 53., 22.,
       54., 67., 10., 79., 17., 56., 29., 48., 25., 21.,  2., 49., 44.,
       82., 15., 46., 18., 33., 47., 65.,  6., 75., 70.,  8., 30., 72.,
        5., 85., 12., 87., 86., 81., 78., 13., 84.,  0.,  1.])

In [48]:
df['Age'].nunique()

88

In [49]:
df['Private Attorney'].unique()

array(['1', '0', nan, 'Auto%#'], dtype=object)

In [50]:
df['Private Attorney'].nunique()

3

In [51]:
df['Marital Status'].unique()

array([nan,  2.,  1.,  4.,  0.,  3.])

In [52]:
df['Marital Status'].nunique()

5

In [53]:
df['Specialty'].unique()

array(['Family Practice', nan, 'Cardiology', 'Pediatrics', 'OBGYN',
       'Internal Medicine', 'Anesthesiology', 'Emergency Medicine',
       'Ophthamology', 'Urological Surgery', 'Orthopedic Surgery',
       'Neurology/Neurosurgery', 'Occupational Medicine', 'Resident',
       'Thoracic Surgery', 'General Surgery', 'Radiology', 'Pathology',
       'Physical Medicine', 'Plastic Surgeon', 'Auto%#', 'Dermatology'],
      dtype=object)

In [54]:
df['Specialty'].nunique()

21

In [55]:
df['Insurance'].unique()

array(['Private', 'No Insurance', 'Unknown', 'Medicare/Medicaid', nan,
       'Workers Compensation'], dtype=object)

In [56]:
df['Insurance'].nunique()

5

In [57]:
df['Gender'].unique()

array(['Male', 'Female', 'Auto%#', nan], dtype=object)

In [58]:
df['Gender'].nunique()

3

In [59]:
df.duplicated().sum()

np.int64(8463)

In [60]:
df.isnull().sum()

Amount              2837
Severity            2837
Age                 2837
Private Attorney    2837
Marital Status      4676
Specialty           2837
Insurance           2837
Gender              2837
dtype: int64

In [61]:
df.isnull()

Amount  Severity    Age  Private Attorney  Marital Status  Specialty  \
0       False     False  False             False            True      False   
1       False     False  False             False           False       True   
2       False     False  False             False           False      False   
3       False     False  False             False           False      False   
4       False     False  False             False           False      False   
...       ...       ...    ...               ...             ...        ...   
94589   False     False  False             False           False      False   
94590   False     False  False             False           False      False   
94591   False     False  False             False           False      False   
94592   False     False  False             False           False      False   
94593   False     False  False             False           False      False   

       Insurance  Gender  
0          False   False  
1          False   False  
2          False   False  
3          False   False  
4          False   False  
...          ...     ...  
94589      False   False  
94590      False   False  
94591      False   False  
94592      False   False  
94593      False   False  

[94594 rows x 8 columns]

In [62]:
lista_col=df.columns
df1=df
for i in lista_col:
    df1=df1[df1[i] != 'invalid_value']
df1

Amount  Severity   Age Private Attorney  Marital Status  \
0       57041.0       7.0  62.0                1             NaN   
1      324976.0       6.0  38.0                1             2.0   
2      135383.0       4.0  34.0                1             2.0   
3      829742.0       7.0  42.0                1             1.0   
4      197675.0       3.0  60.0                0             2.0   
...         ...       ...   ...              ...             ...   
94589  146059.0       3.0  56.0                0             2.0   
94590  908341.0       8.0  35.0                1             2.0   
94591   39355.0       3.0  42.0                0             4.0   
94592  827167.0       6.0  57.0                1             0.0   
94593  134090.0       9.0  63.0                1             4.0   

                    Specialty          Insurance  Gender  
0             Family Practice            Private    Male  
1                         NaN       No Insurance  Female  
2                  Cardiology            Unknown    Male  
3                  Pediatrics       No Insurance  Female  
4                       OBGYN  Medicare/Medicaid  Female  
...                       ...                ...     ...  
94589                   OBGYN            Unknown  Female  
94590      Orthopedic Surgery            Unknown    Male  
94591      Emergency Medicine  Medicare/Medicaid    Male  
94592             Dermatology            Private    Male  
94593  Neurology/Neurosurgery  Medicare/Medicaid  Female  

[94594 rows x 8 columns]

In [63]:
for i in lista_col:
    print(f"En la columna {i} los invalid_value son: {df1[df1[i] == 'invalid_value'].shape[0]}")

En la columna Amount los invalid_value son: 0
En la columna Severity los invalid_value son: 0
En la columna Age los invalid_value son: 0
En la columna Private Attorney los invalid_value son: 0
En la columna Marital Status los invalid_value son: 0
En la columna Specialty los invalid_value son: 0
En la columna Insurance los invalid_value son: 0
En la columna Gender los invalid_value son: 0


In [64]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94594 entries, 0 to 94593
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Amount            91757 non-null  float64
 1   Severity          91757 non-null  float64
 2   Age               91757 non-null  float64
 3   Private Attorney  91757 non-null  object 
 4   Marital Status    89918 non-null  float64
 5   Specialty         91757 non-null  object 
 6   Insurance         91757 non-null  object 
 7   Gender            91757 non-null  object 
dtypes: float64(4), object(4)
memory usage: 5.8+ MB


In [65]:
df1.isnull().sum()

Amount              2837
Severity            2837
Age                 2837
Private Attorney    2837
Marital Status      4676
Specialty           2837
Insurance           2837
Gender              2837
dtype: int64

In [66]:
df1['Amount'] = pd.to_numeric(df1['Amount'], errors='coerce')
df1

Amount  Severity   Age Private Attorney  Marital Status  \
0       57041.0       7.0  62.0                1             NaN   
1      324976.0       6.0  38.0                1             2.0   
2      135383.0       4.0  34.0                1             2.0   
3      829742.0       7.0  42.0                1             1.0   
4      197675.0       3.0  60.0                0             2.0   
...         ...       ...   ...              ...             ...   
94589  146059.0       3.0  56.0                0             2.0   
94590  908341.0       8.0  35.0                1             2.0   
94591   39355.0       3.0  42.0                0             4.0   
94592  827167.0       6.0  57.0                1             0.0   
94593  134090.0       9.0  63.0                1             4.0   

                    Specialty          Insurance  Gender  
0             Family Practice            Private    Male  
1                         NaN       No Insurance  Female  
2                  Cardiology            Unknown    Male  
3                  Pediatrics       No Insurance  Female  
4                       OBGYN  Medicare/Medicaid  Female  
...                       ...                ...     ...  
94589                   OBGYN            Unknown  Female  
94590      Orthopedic Surgery            Unknown    Male  
94591      Emergency Medicine  Medicare/Medicaid    Male  
94592             Dermatology            Private    Male  
94593  Neurology/Neurosurgery  Medicare/Medicaid  Female  

[94594 rows x 8 columns]

In [67]:
df1['Amount'].fillna(df1['Amount'].mean(), inplace=True)
df1

Amount  Severity   Age Private Attorney  Marital Status  \
0       57041.0       7.0  62.0                1             NaN   
1      324976.0       6.0  38.0                1             2.0   
2      135383.0       4.0  34.0                1             2.0   
3      829742.0       7.0  42.0                1             1.0   
4      197675.0       3.0  60.0                0             2.0   
...         ...       ...   ...              ...             ...   
94589  146059.0       3.0  56.0                0             2.0   
94590  908341.0       8.0  35.0                1             2.0   
94591   39355.0       3.0  42.0                0             4.0   
94592  827167.0       6.0  57.0                1             0.0   
94593  134090.0       9.0  63.0                1             4.0   

                    Specialty          Insurance  Gender  
0             Family Practice            Private    Male  
1                         NaN       No Insurance  Female  
2                  Cardiology            Unknown    Male  
3                  Pediatrics       No Insurance  Female  
4                       OBGYN  Medicare/Medicaid  Female  
...                       ...                ...     ...  
94589                   OBGYN            Unknown  Female  
94590      Orthopedic Surgery            Unknown    Male  
94591      Emergency Medicine  Medicare/Medicaid    Male  
94592             Dermatology            Private    Male  
94593  Neurology/Neurosurgery  Medicare/Medicaid  Female  

[94594 rows x 8 columns]

In [68]:
columna = 'Severity'
num_nulos = df1[columna].isnull().sum()
numeros_enteros = np.random.randint(1, 10, size=num_nulos)
numeros_flotantes = numeros_enteros.astype(float) 
serie_reemplazo = pd.Series(
    numeros_flotantes,
    index=df1[df1[columna].isnull()].index
)

df1[columna].fillna(serie_reemplazo, inplace=True)

In [69]:
df1.isnull().sum()

Amount                 0
Severity               0
Age                 2837
Private Attorney    2837
Marital Status      4676
Specialty           2837
Insurance           2837
Gender              2837
dtype: int64

In [70]:
columna = 'Age'
num_nulos = df1[columna].isnull().sum()
numeros_enteros = np.random.randint(25, 75, size=num_nulos)
numeros_flotantes = numeros_enteros.astype(float) 
serie_reemplazo = pd.Series(
    numeros_flotantes,
    index=df1[df1[columna].isnull()].index
)

df1[columna].fillna(serie_reemplazo, inplace=True)

In [71]:
columna = 'Private Attorney'
num_nulos = df1[columna].isnull().sum()
numeros_enteros = np.random.randint(0, 1, size=num_nulos)
numeros_flotantes = numeros_enteros.astype(float) 
serie_reemplazo = pd.Series(
    numeros_flotantes,
    index=df1[df1[columna].isnull()].index
)

df1[columna].fillna(serie_reemplazo, inplace=True)

In [72]:
df1.isnull().sum()

Amount                 0
Severity               0
Age                    0
Private Attorney       0
Marital Status      4676
Specialty           2837
Insurance           2837
Gender              2837
dtype: int64

In [73]:
columna = 'Marital Status'
num_nulos = df1[columna].isnull().sum()
numeros_enteros = np.random.randint(1, 4, size=num_nulos)
numeros_flotantes = numeros_enteros.astype(float) 
serie_reemplazo = pd.Series(
    numeros_flotantes,
    index=df1[df1[columna].isnull()].index
)

df1[columna].fillna(serie_reemplazo, inplace=True)

In [74]:
columna = 'Marital Status'
num_nulos = df1[columna].isnull().sum()
numeros_enteros = np.random.randint(1, 4, size=num_nulos)
numeros_flotantes = numeros_enteros.astype(float) 
serie_reemplazo = pd.Series(
    numeros_flotantes,
    index=df1[df1[columna].isnull()].index
)

df1[columna].fillna(serie_reemplazo, inplace=True)
df1

Amount  Severity   Age Private Attorney  Marital Status  \
0       57041.0       7.0  62.0                1             1.0   
1      324976.0       6.0  38.0                1             2.0   
2      135383.0       4.0  34.0                1             2.0   
3      829742.0       7.0  42.0                1             1.0   
4      197675.0       3.0  60.0                0             2.0   
...         ...       ...   ...              ...             ...   
94589  146059.0       3.0  56.0                0             2.0   
94590  908341.0       8.0  35.0                1             2.0   
94591   39355.0       3.0  42.0                0             4.0   
94592  827167.0       6.0  57.0                1             0.0   
94593  134090.0       9.0  63.0                1             4.0   

                    Specialty          Insurance  Gender  
0             Family Practice            Private    Male  
1                         NaN       No Insurance  Female  
2                  Cardiology            Unknown    Male  
3                  Pediatrics       No Insurance  Female  
4                       OBGYN  Medicare/Medicaid  Female  
...                       ...                ...     ...  
94589                   OBGYN            Unknown  Female  
94590      Orthopedic Surgery            Unknown    Male  
94591      Emergency Medicine  Medicare/Medicaid    Male  
94592             Dermatology            Private    Male  
94593  Neurology/Neurosurgery  Medicare/Medicaid  Female  

[94594 rows x 8 columns]

In [75]:
df1['Specialty'].fillna(df1['Specialty'].mode()[0], inplace=True)

In [77]:
df1['Insurance'].fillna(df1['Insurance'].mode()[0], inplace=True)

In [78]:
df1['Gender'].fillna(df1['Gender'].mode()[0], inplace=True)

In [79]:
df1.isnull().sum()

Amount              0
Severity            0
Age                 0
Private Attorney    0
Marital Status      0
Specialty           0
Insurance           0
Gender              0
dtype: int64